baseURL = "https://vincentvansetten.com"
languageCode = "en-us"
title = "Vincent van Setten"
theme = "coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
  author = "Vincent van Setten"
  info = "Student Developer & Linux Enthusiast"
  description = "Vincent van Setten's personal portfolio website"
  keywords = "blog,developer,personal,student,linux"
  avatarurl = "images/avatar.jpg"
  #gravatar = "vvampus@gmail.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  footercontent = "Powered by Free and Open Source Software"
  hideFooter = false
  hideCredits = true
  hideCopyright = false
  since = 2018

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/Vvamp/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://linkedin.com/in/vincentvansetten"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3 
  url = "https://twitter.com/Vvamp_/"
[[params.social]]
  name = "Facebook"
  icon = "fa fa-facebook fa-2x"
  weight = 4 
  url = "https://facebook.com/vincent.vansetten/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url  = "projects/"
[[menu.main]]
  name = "Resume"
  weight = 4
  url  = "resume/"
[[menu.main]]
  name = "Contact"
  weight = 5
  url  = "contact/"
[markup.goldmark.renderer]
unsafe = true
[blackfriday]
  hrefTargetBlank = true
